// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanOldBackups(arg1) {
  return window['go']['main']['App']['CleanOldBackups'](arg1);
}

export function ConfigureCloud() {
  return window['go']['main']['App']['ConfigureCloud']();
}

export function DetectConfig() {
  return window['go']['main']['App']['DetectConfig']();
}

export function GetCloudBackups(arg1) {
  return window['go']['main']['App']['GetCloudBackups'](arg1);
}

export function GetCloudProjects() {
  return window['go']['main']['App']['GetCloudProjects']();
}

export function GetCloudQuota() {
  return window['go']['main']['App']['GetCloudQuota']();
}

export function IsCloudConfigured() {
  return window['go']['main']['App']['IsCloudConfigured']();
}

export function LoadExclusions() {
  return window['go']['main']['App']['LoadExclusions']();
}

export function SaveExclusions(arg1) {
  return window['go']['main']['App']['SaveExclusions'](arg1);
}

export function SetProjectPath(arg1) {
  return window['go']['main']['App']['SetProjectPath'](arg1);
}

export function StartBackup(arg1, arg2) {
  return window['go']['main']['App']['StartBackup'](arg1, arg2);
}

export function StartRestore(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartRestore'](arg1, arg2, arg3);
}
