// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CleanOldBackups(arg1:boolean):Promise<void>;

export function ConfigureCloud():Promise<void>;

export function DetectConfig():Promise<main.ProjectConfig>;

export function GetCloudBackups(arg1:string):Promise<Array<main.BackupFile>>;

export function GetCloudProjects():Promise<Array<string>>;

export function GetCloudQuota():Promise<main.CloudQuota>;

export function IsCloudConfigured():Promise<boolean>;

export function LoadExclusions():Promise<main.Exclusions>;

export function SaveExclusions(arg1:main.Exclusions):Promise<void>;

export function SetProjectPath(arg1:string):Promise<main.ProjectConfig>;

export function StartBackup(arg1:boolean,arg2:string):Promise<void>;

export function StartRestore(arg1:string,arg2:string,arg3:boolean):Promise<void>;
